### ISSUE TITLE
raise RuntimeError('Attempting to deserialize object on a CUDA ' RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location='cpu' to map your storages to the CPU.

### ISSUE THREAD

**Issue by zcl912** [SoftwareGift/FeatherNets_Face-Anti-spoofing-Attack-Detection-Challenge-CVPR2019#16]
在运行代码时遇到这个问题，请问该怎么解决呢？其中：
>>> import torch
>>> print(torch.cuda.is_available())
False
>>> 
显卡驱动不匹配的原因吗

**Comment by zcl912** [comment]
> 在运行代码时遇到这个问题，请问该怎么解决呢？其中：
> 
> > > > import torch
> > > > print(torch.cuda.is_available())
> > > > False
> 
> 显卡驱动不匹配的原因吗

已解決

**Comment by Cndbk** [comment]
> > 在运行代码时遇到这个问题，请问该怎么解决呢其中？
> > > > > 进口火炬
> > > > > 打印（torch.cuda.is_available（））
> > > > > 假
> > 
> > 
> > 显卡驱动不匹配的原因吗
> 
> 已解决

求解决办法
